run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - structcheck # deprecated
    - deadcode    # deprecated
    - varcheck    # deprecated
    - golint      # deprecated
    - gomnd       # deprecated, replaced by mnd

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "logging is allowed only by logutils.Log"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/rknightion/adsb2loki)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/rknightion/adsb2loki
  govet:
    enable-all: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    require-explanation: false
    require-specific: false
  revive:
    confidence: 0

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - gosec

    - path: pkg/models/
      linters:
        - revive
        - stylecheck

    - linters:
        - lll
      source: "^//go:generate " 