package flightaware

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/rknightion/adsb2loki/pkg/common"
	"github.com/rknightion/adsb2loki/pkg/models"
)

// FetchAndPushToLoki fetches aircraft data from FlightAware and pushes it to the logger
func FetchAndPushToLoki(ctx context.Context, logger common.Logger) error {
	// Fetch data from FlightAware
	resp, err := http.Get(os.Getenv("AIRCRAFT_JSON_URL"))
	if err != nil {
		return fmt.Errorf("failed to fetch FlightAware data: %w", err)
	}
	defer resp.Body.Close()

	// Parse the response
	var data models.AutoGenerated
	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return fmt.Errorf("failed to decode FlightAware data: %w", err)
	}

	// Convert aircraft data to log entries
	entries := make([]common.LogEntry, 0, len(data.Aircraft))
	for _, aircraft := range data.Aircraft {
		// Create a JSON string of the aircraft data
		aircraftJSON, err := json.Marshal(aircraft)
		if err != nil {
			return fmt.Errorf("failed to marshal aircraft data: %w", err)
		}

		// Create labels for the log
		labels := map[string]string{
			"service": "flightaware",
		}

		// Create the log entry
		entry := common.LogEntry{
			Timestamp: time.Unix(int64(data.Now), 0),
			Labels:    labels,
			Line:      string(aircraftJSON),
		}

		entries = append(entries, entry)
	}

	// Push to the logger
	if err := logger.PushLogs(ctx, entries); err != nil {
		return fmt.Errorf("failed to push logs: %w", err)
	}

	return nil
}
