package models

type AutoGenerated struct {
	Now      float64 `json:"now"`
	Messages int     `json:"messages"`
	Aircraft []struct {
		Hex            string        `json:"hex"`
		Flight         string        `json:"flight,omitempty"`
		AltBaro        int           `json:"alt_baro,omitempty"`
		AltGeom        int           `json:"alt_geom,omitempty"`
		Gs             float64       `json:"gs,omitempty"`
		Ias            int           `json:"ias,omitempty"`
		Tas            int           `json:"tas,omitempty"`
		Mach           float64       `json:"mach,omitempty"`
		Track          float64       `json:"track,omitempty"`
		TrackRate      float64       `json:"track_rate,omitempty"`
		Roll           float64       `json:"roll,omitempty"`
		MagHeading     float64       `json:"mag_heading,omitempty"`
		BaroRate       int           `json:"baro_rate,omitempty"`
		GeomRate       int           `json:"geom_rate,omitempty"`
		Squawk         string        `json:"squawk,omitempty"`
		Emergency      string        `json:"emergency,omitempty"`
		Category       string        `json:"category,omitempty"`
		NavQnh         float64       `json:"nav_qnh,omitempty"`
		NavAltitudeMcp int           `json:"nav_altitude_mcp,omitempty"`
		NavHeading     float64       `json:"nav_heading,omitempty"`
		Lat            float64       `json:"lat,omitempty"`
		Lon            float64       `json:"lon,omitempty"`
		Nic            int           `json:"nic,omitempty"`
		Rc             int           `json:"rc,omitempty"`
		SeenPos        float64       `json:"seen_pos,omitempty"`
		Version        int           `json:"version,omitempty"`
		NicBaro        int           `json:"nic_baro,omitempty"`
		NacP           int           `json:"nac_p,omitempty"`
		NacV           int           `json:"nac_v,omitempty"`
		Sil            int           `json:"sil,omitempty"`
		SilType        string        `json:"sil_type,omitempty"`
		Gva            int           `json:"gva,omitempty"`
		Sda            int           `json:"sda,omitempty"`
		Mlat           []interface{} `json:"mlat"`
		Tisb           []interface{} `json:"tisb"`
		Messages       int           `json:"messages"`
		Seen           float64       `json:"seen"`
		Rssi           float64       `json:"rssi"`
		NavAltitudeFms int           `json:"nav_altitude_fms,omitempty"`
		NavModes       []string      `json:"nav_modes,omitempty"`
	} `json:"aircraft"`
}
