# Example OpenTelemetry Collector configuration for receiving logs from adsb2loki

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 10s

exporters:
  # Example: Export to Loki via OpenTelemetry
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
    labels:
      attributes:
        service: "service"
    
  # Example: Export to stdout for debugging
  debug:
    verbosity: detailed

  # Example: Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

  telemetry:
    logs:
      level: info 